apiVersion: v1
kind: Service
metadata:
  name: postgresql-service-compras
spec:
  selector:
    app: postgresql
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001 # Puedes cambiar el puerto si lo necesitas

